version: '3'

services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: scdb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080

  redis:
    image: redis:latest
    ports:
      - 6378:6379

#  application:
#    container_name: springboot
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - 8080:8080
#    depends_on:
#      - postgres
#      - redis

